name: Build

on:
    push:
        branches:
            - main
    pull_request:

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v3
            -   name: Install JDK 21
                uses: actions/setup-java@v3
                with:
                    distribution: temurin
                    java-version: 21
            -   name: Build
                run: mvn -B install
